all: install

install:
	git clone https://github.com/knolleary/pubsubclient --progress --branch v2.6 --single-branch pubsubclient
	git clone https://github.com/esp8266/Arduino/ --progress --branch 2.3.0 --single-branch esp8266

clean:
	rm -rf pubsubclient esp8266
